### ISSUE TITLE
Inconsistent dropdown behavior

### ISSUE THREAD

**Issue by karlmacklin** [clalil/BMI_Challenge#1]
When opening the dropdown for unit system selection, the imperial box is immediately appended below the metric one.
Expected to keep the metric alone, and only switch to the imperial one after selecting it in the dropdown.

Tested without web server, directly opening html file from file system in Chrome.

See image for problem in action:

![image](https://user-images.githubusercontent.com/353806/69808298-7b2ebe80-11e7-11ea-96ec-439442480ab8.png)

**Comment by clalil** [comment]
Thank you for noticing, this was an old ITP course project, so have not have time yet to look over it. Updated the files with a minor PR to solve it.
